- name: install common packages
  hosts: all
  vars:
    nodejs_version: 21
    dotfiles_home: ~/.config
    dotfiles_repo: ~/git/dotfiles
    dotfiles_repo_url: git@github.com:Picole9/dotfiles.git
    http_proxy: 
    https_proxy:
  roles:
    - dotfiles
    - common
    - glow
    - nvim
    - fish
