- name: legacy install with less dependencies
  hosts: all
  roles:
    - common
    - fonts
    - nvim-legacy
    - fish
    - glow
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
