- name: Install packages
  tags: install
  become: true
  ansible.builtin.package:
    name: tealdeer
    state: present

- name: Set config
  tags: configure
  ansible.builtin.import_role:
    name: dotfiles
  vars:
    dotfiles_link_config: tealdeer

- name: Update tldr
  tags: update
  ansible.builtin.shell: "tldr --update"
