- name: Install packages
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Set config
  ansible.builtin.import_role:
    name: dotfiles
  vars:
    dotfiles_link_config: nvim
    dotfiles_link_config_name: nvim-legacy
