- name: Ensure dotfiles repository is cloned locally.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ dotfiles_repo }}"
    version: main
    accept_newhostkey: true
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Create config dir
  ansible.builtin.file:
    path: "{{ dotfiles_home }}"
    state: directory
    mode: "0777"
