- name: Install packages
  block:
    - name: Debian specific
      ansible.builtin.import_tasks: debian.yaml
      when: ansible_os_family == "Debian"
    - name: Arch specific
      ansible.builtin.import_tasks: arch.yaml
      when: ansible_os_family == "Archlinux"

- name: Set config
  ansible.builtin.import_role:
    name: dotfiles
  vars:
    dotfiles_link_config: glow
