- name: Create ssh key for user
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user_id }}/.ssh/id_rsa"
    size: 4096

- name: Copy id
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
