- name: Arch-specific
  tags: install
  ansible.builtin.import_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Install keys
  tags: configure
  block:
    - name: Ensure folder exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/aacs"
        state: directory
        mode: "0777"
    - name: Download db
      ansible.builtin.get_url:
        url: https://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg
        dest: "{{ ansible_env.HOME }}/.config/aacs/KEYDB.cfg"
        mode: "0777"
