- name: Install packages
  block:
    - name: Debian specific
      ansible.builtin.import_tasks: debian.yaml
      when: ansible_os_family == "Debian"
    - name: Arch specific
      ansible.builtin.import_tasks: arch.yaml
      when: ansible_os_family == "Archlinux"

- name: Configure wezterm
  block:
    - name: Clone dotfiles
      ansible.builtin.import_role:
        name: dotfiles
    - name: Ensure configured dotfiles are links.
      ansible.builtin.command: "ls -F {{ dotfiles_home }}/wezterm/wezterm.lua"
      register: existing_dotfile_info
      changed_when: false
      failed_when: false
    - name: Remove old dotfiles
      ansible.builtin.file:
        path: "{{ dotfiles_home }}/wezterm/wezterm.lua"
        state: absent
      when: "'@' not in existing_dotfile_info.stdout"
    - name: Link config
      ansible.builtin.file:
        src: "{{ dotfiles_repo }}/.wezterm.lua"
        dest: "{{ dotfiles_home }}/wezterm/wezterm.lua"
        state: link
      when: "'@' not in existing_dotfile_info.stdout"
- name: Add fish autocompletion
  ansible.builtin.shell: "wezterm shell-completion --shell fish > {{ dotfiles_home }}/fish/completions/wezterm.fish"
  args:
    creates: "{{ dotfiles_home }}/fish/completions/wezterm.fish"
