- name: Install packages
  block:
    - name: Debian specific
      ansible.builtin.import_tasks: debian.yaml
      when: ansible_os_family == "Debian"
    - name: Arch specific
      ansible.builtin.import_tasks: arch.yaml
      when: ansible_os_family == "Archlinux"

- name: Set config
  ansible.builtin.import_role:
    name: dotfiles
  vars:
    dotfiles_link_config: wezterm/wezterm.lua
    dotfiles_link_config_name: wezterm.lua

- name: Add fish autocompletion
  ansible.builtin.shell: "wezterm shell-completion --shell fish > {{ ansible_env }}/.config/fish/completions/wezterm.fish"
  args:
    creates: "{{ ansible_env }}/.config/fish/completions/wezterm.fish"
