- name: install packages
  become: true
  community.general.pacman:
    name:
      - bat # cat
      - exa # ls
      - ripgrep # grep
      - fd # find
      - btop # htop
      - universal-ctags
      - ca-certificates
      - curl
      - git
      - gnupg
      - tldr
      - nodejs
      - npm
      - tar
      - python-pip
      - python-virtualenv
      - unzip
