- name: Install packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - bat # cat
      - btop # htop
      - ca-certificates
      - curl
      - fd-find # find
      - git
      - gnupg
      - python3-pip
      - python3-venv
      - ripgrep # grep
      - software-properties-common
- name: Install pip-packages
  ansible.builtin.pip:
    name:
      - tldr
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    PIP_BREAK_SYSTEM_PACKAGES: "1"
- name: Install eza # ls
  block:
    - name: Check for eza
      ansible.builtin.command: apt-cache policy eza
      register: eza_exists
      changed_when: false
      failed_when: false
    - name: Install eza
      become: true
      ansible.builtin.apt:
        name: eza
      when: "'Candidate' in eza_exists.stdout"
    - name: Install exa if eza does not exist
      become: true
      ansible.builtin.apt:
        name: exa
      when: "'Candidate' not in eza_exists.stdout"

- name: Gather packages facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install font
  when: "'fc-cache' in ansible_facts.packages"
  block:
    - name: Ensure font folder exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: "0777"
    - name: Download font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hasklig.tar.xz
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"
        remote_src: true
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
    - name: Update font-cache
      ansible.builtin.command: "fc-cache -f"
