- import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- import_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: install font
  block:
    - name: ensure font folder exist
      file:
        path: "/home/{{ ansible_user_id }}/.local/share/fonts"
        state: directory
    - name: download font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hasklig.tar.xz
        dest: "/home/{{ ansible_user_id }}/.local/share/fonts"
        remote_src: yes
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
    - name: update font-cache
      shell: "fc-cache -f"
