- name: Install packages
  community.general.pacman:
    name:
      - curl
      - fd
      - fzf
      - git
      - gzip
      - neovim
      - npm
      - python-neovim
      - ripgrep
      - tar
      - unzip
    state: present
  become: true
