- name: Install packages
  block:
    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "ppa:neovim-ppa/unstable"
        state: present
      become: true
    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
          - git
          - gzip
          - neovim
          - npm
          - tar
          - universal-ctags
          - unzip
        state: present
        update_cache: true
      become: true
