- name: add repo
  ansible.builtin.apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
  become: true
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
- name: install packages
  ansible.builtin.apt: 
    name: neovim
    state: present
    update_cache: true
  become: true
